export const LOGIN_USER="LOGIN_USER"
export const SIGNOUT_USER="SIGNOUT_USER"
export const SIGNUP_USER="SIGNUP_USER"
export const SET_LOADING="SET_LOADING"
export const SET_USER = "SET_USER";
export const RESET_USER = "RESET_USER";
export const ADD_CONTENT =" ADD_CONTENT"
export const GET_CONTENT_REQUEST =" GET_CONTENT_REQUEST"
export const GET_CONTENT_SUCCESS=" FETCH_CONTENT_SUCCESS"
export const GET_CONTENT_FAILURE="FETCH_CONTENT_FAILURE"
export const UPDATE_CONTENT =" UPDATE_CONTENT"
export const GET_UPDATE_CONTENT = "GET_UPDATE_CONTENT"
export const DELETE_CONTENT =" DELETE_CONTENT"













